name: Test workflow
on:
  pull_request:
    # types: [opened, reopened]
    # branches:
    #   - prerelease

  workflow_dispatch:
    inputs:
      build_tag:
        description: "Which build tag to use (default is 'blah' for env1 and 'blah2' for env2"
        required: false
        type: string

jobs:
  check_task_format_compatibility:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          clean: false

      - name: "Run test script for env1"
        run: |
          python3 test.py -t ${{ github.event.inputs.build_tag || 'blah' }} -e ENV1

      - name: "Run test script for env2"
        run: |
          python3 test.py -t ${{ github.event.inputs.build_tag || 'blah2' }} -e ENV2

      # - name: "Run check compatibility script for EDU"
      #   run: python3 backend/kialo/applications/development/check_task_formats.py -t deployed-edu-prod -e edu
