name: Test workflow
on:
  pull_request:
    # types: [opened, reopened]
    # branches:
    #   - prerelease

  workflow_dispatch:
    inputs:
      build_tag:
        description: "Which build tag to use against"
        required: false
        default: ""
        type: string

jobs:
  check_task_format_compatibility:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          clean: false

      - name: "Run test script"
        run: python3 test.py -t build-tag -e environment

      # - name: "Run check compatibility script for EDU"
      #   run: python3 backend/kialo/applications/development/check_task_formats.py -t deployed-edu-prod -e edu
